version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # do not map node_modules, and use the node_modules folder inside docker container.
      - /app/node_modules
      # map everything else. Easier for development locally, quick refresh without docker build.
      - .:/app

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    # The below command will overwrite the start-up command mentioned inside dockerfile.
    command: ["npm", "run", "test"]